// Any app specific constants that you don't want to keep in config can go here.
export const GOOGLE_AUTH_TOKEN = "GOOGLE_AUTH_TOKEN";
export const SIGNUP_OPERATION = "SIGNUP";
export const LOGIN_OPERATION = "LOGIN";
export const USER_YOUTUBE_ACCESS_TOKEN = "USER_YOUTUBE_ACCESS_TOKEN";
export const USER_YOUTUBE_ACCOUNT_DATA = "USER_YOUTUBE_ACCOUNT_DATA";
export const USER_FACEBOOK_USER_DATA = "USER_FACEBOOK_USER_DATA";
export const FACEBOOK_PAGE_DATA = "FACEBOOK_PAGE_DATA";
export const YOUTUBE_CHANNEL_THUMBNAIL_URL = "YOUTUBE_CHANNEL_THUMBNAIL_URL";
export const FACEBOOK_PAGE_PROFILE_IMAGE = "FACEBOOK_PAGE_PROFILE_IMAGE";
